#!/bin/bash
# runs all the tests in the tests/ subdirectory, using tewiba (provided)
# Options: -v for verbose mode
#          -? for help

# Change dir to where this script is
scriptpath=$(realpath $(which "$0"))
cd "${scriptpath%/*}" || exit 1

# Sanity check: stop immediately if we have a syntax error in bash scripts
ok=true
for i in $(find -type f -executable); do 
    if grep -q '^#! */bin/bash' < <(head -1 "$i") && [ -x "$i" ]; then
	bash -n "$i" || ok=false
    fi
done
$ok || { echo "***ABORTING: syntax errors in scripts" >&2; exit 1; }

# otherwise, run all the *.test files in the tests/ dir in alphabetical order
# to run a single test, go into tests and run it directly (verbose mode)
# or as argument to tewiba (terse mode), e.g: cd tests; tewiba foo.test
# we look for the tewiba executable in tests/ or above, or on the system

cd tests || exit 1

if [ -x tewiba ]; then tewiba=./tewiba
elif [ -x ../tewiba ]; then tewiba=../tewiba
else tewiba=tewiba
fi

for test in *.test; do
    [ "$test" != "*.test" ] && $tewiba $* "$test"
done
