#!/bin/bash
error="testshell run without argument"
error () { echo "$error $*" >&2; let fails++; }
fails=0

res=$(../testshell)

[ $? = 0 ] \
  && error "did not return an error"

[[ $res =~ ^testshell\ [[]options[]]\ [[]tests[.][.][.][]] ]] \
  || error "did not print the usage"

exit $fails