#!/bin/bash
[ -n "$TEWIBA" ] || exec tewiba -v "$0"

res=$(../tewiba -bogus)

[ $? = 0 ] \
  && TERR "did not return an error"

[[ $res =~ ^tewiba\ [[]options[]]\ [[]tests[.][.][.][]] ]] \
  || TERR "did not print the usage"

TEND
