#!/bin/bash
[ -n "$TESTSHELL" ] || exec testshell -v "$0"

res=$(../testshell -bogus)

[ $? = 0 ] \
  && TERR "did not return an error"

[[ $res =~ ^testshell\ [[]options[]]\ [[]tests[.][.][.][]] ]] \
  || TERR "did not print the usage"

TEND
